FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    jq \
    git \
    libicu70 \
    libkrb5-3 \
    libssl3 \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

ARG RUNNER_UID=999
RUN useradd -m -u ${RUNNER_UID} runner

WORKDIR /home/runner

ENV RUNNER_VERSION=2.322.0

RUN curl -L -O https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && rm actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

ENV PACKER_VERSION=${PACKER_VERSION}
# Download and install Packer using the parameterized version
RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip \
    && unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && rm packer_${PACKER_VERSION}_linux_amd64.zip
    
# Copy the entrypoint script to /opt so it won’t be overridden by the volume mount
COPY --chmod=0755 entrypoint.sh /opt/entrypoint.sh

USER runner

# Set the entrypoint from the /opt directory
ENTRYPOINT ["/opt/entrypoint.sh"]

