name: Packer Image Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    runs-on: self-hosted  # Ensure your self-hosted runner has Packer installed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run `packer init`
        working-directory: ubuntu22
        id: init
        run: "packer init ./ubuntu22.pkr.hcl"

      - name: Build Ubuntu 22 Image
        working-directory: ubuntu22
        env:
          VCENTER_USERNAME: ${{ vars.VCENTER_USERNAME }}
          VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          VCENTER_SERVER: ${{ vars.VCENTER_SERVER }}
        run: |
          packer build -force \
            -var-file "ubuntu22.pkrvars.hcl"
            -var "vsphere_username=${VCENTER_USERNAME}" \
            -var "vsphere_password=${VCENTER_PASSWORD}" \
            -var "vsphere_server=${VCENTER_SERVER}" \
            -var "vsphere_guest_os_type=ubuntu64Guest" \
            -var "vsphere_vm_name=ubuntu-22-temp" \
            -var "template_library_Name=ubuntu22" \
            -var "content_library_destination=vcenter.int.sentania.net" .
